language: cpp
dist: trusty
sudo: required

env:
  global:
    - DEPLOY_ARCHIVE=${TRAVIS_BUILD_DIR}/dist/dr-breakpad-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.xz

install: ./scripts/travis-install-${TRAVIS_OS_NAME}.sh

before_script:
- qbs setup-toolchains --detect
- qbs config defaultProfile ${QBS_PROFILE}

matrix:
  include:
  - os: linux
    env: QBS_PROFILE=gcc PATH=/opt/qt58/bin:$PATH
  - os: osx
    env: QBS_PROFILE=clang

script:
- qbs install --install-root dist -p breakpad_client config:debug
- qbs install --install-root dist config:release
- tree ./dist

after_success:
- pushd dist && tar -cvJf ${DEPLOY_ARCHIVE} * ; popd

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SYxpaHxJ5f2gOYPHNDRUqKy6XqKhIujdfSeAHiBIpOu3PnGodSQnpR5a0Mx+KWj+2zhQ4Q7sNlfNZhvLeNhvIpbek4mqd+ndbqgA52Qy38GtR55bwlZolXi8tVcCHDrKn6DHlVxwKCOGtZrzhaYSXjr0dZUdXVuChr8jd1jvpG9qT7cP9A9wBujjjmF8ordk97vzNkoLLz8iXtg6Gk6DRSo/5hJBAxwSH00q8cKnZJwE4lIvWozJEK4QfklYbDfC06rR7oHZUebqRUJwHE2PbEiA0ImOs9b2EXr6vJABtCNZrxXLwav3/11mHIxa1yC/3ZJBESBzKzvum7F1vrcxXJQZyxY5QXWC/zQRXXDGw0Q7HTMBkygJKj9IEv2ly6n9URLIcDYgJzN5Jf/tRaJUl8nVwx7kau9E4I7YaLfu8cvK7+XFgMQUIbtOqIOiigZagz5onXP1aNo15m4/GHvGZFlr0NcMi2x8L89pjjRtDJkoicSIZgxIl9+8cejOkPjP2s2Fxkd12ItZkohpMPN8OyKKizvSfDEqiLND4+dh5ZgnEXXN1d6SyrSYUHT9tG8YSULtoqu4j0AIHfeg12nAl/bSDhvtH/+WwE2BpLsGSCiaYh/G3nrc5DjU7CCkKeIh9hMRnJGwfSrB1BMT+yKLtjJ+isXymVtS9b/byRJ//QE=
  file: ${DEPLOY_ARCHIVE}
  on:
    repo: d-ronin/breakpad
    tags: true
